<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KurikulumTrinSeeder extends Seeder
{
    public function run(): void
    {
        // Seed Roles


        // Seed CPLs
        DB::table('cpls')->insert([
            ['id' => 1, 'kode' => 'CPL-01', 'deskripsi' => 'Lulusan mampu melakukan pengelolaan data science, komputasi, dan dasar-dasar rekayasa pada prosedur, proses, maupun sistem keteknikan terapan.', 'created_at' => '2026-05-09 20:27:24', 'updated_at' => '2026-05-09 20:27:24'],
            ['id' => 2, 'kode' => 'CPL-02', 'deskripsi' => 'Lulusan mampu merancang dan mengembangkan sistem dengan unjuk kerja baik dan memiliki kemampuan cerdas.', 'created_at' => '2026-05-09 20:27:34', 'updated_at' => '2026-05-09 20:27:34'],
            ['id' => 4, 'kode' => 'CPL-03', 'deskripsi' => 'Lulusan mampu merancang dan mengembangkan solusi teknologi rekayasa yang komprehensif dengan mengintegrasikan standar keselamatan, efisiensi sumber daya, dan dampak lingkungan hidup', 'created_at' => '2026-05-09 20:28:02', 'updated_at' => '2026-05-09 20:28:02'],
            ['id' => 5, 'kode' => 'CPL-04', 'deskripsi' => 'Lulusan mampu melakukan pengelolaan data dan informasi dalam skala enterprise, dapat melakukan pemantauan data dan informasi secara realtime dan mampu melakukan pemeliharaan sistem.', 'created_at' => '2026-05-09 20:28:17', 'updated_at' => '2026-05-09 20:28:17'],
            ['id' => 6, 'kode' => 'CPL-05', 'deskripsi' => 'Lulusan memiliki kemampuan melakukan integrasi antar sistem untuk proses otomatisasi, memiliki keterampilan berpikir kritis dalam memecahkan masalah kompleks pada bidang pengembangan perangkat lunak dan dapat mengekspresikan ide-ide yang kompleks dan canggih dengan jelas menggunakan berbagai format dan media.', 'created_at' => '2026-05-09 20:28:28', 'updated_at' => '2026-05-09 20:28:28'],
            ['id' => 7, 'kode' => 'CPL-06', 'deskripsi' => 'Lulusan mampu menganalisis dan mengevaluasi dampak dari solusi permasalahan teknik terhadap aspek sosial, ekonomi, keberlanjutan lingkungan, kesehatan dan keselamatan, serta kepatuhan hukum.', 'created_at' => '2026-05-09 20:28:40', 'updated_at' => '2026-05-09 20:28:40'],
            ['id' => 8, 'kode' => 'CPL-07', 'deskripsi' => 'Lulusan mampu berkomitmen pada kode etik profesi dan standar praktik teknologi rekayasa dengan menjunjung tinggi kepatuhan hukum.', 'created_at' => '2026-05-09 20:28:50', 'updated_at' => '2026-05-09 20:28:50'],
            ['id' => 9, 'kode' => 'CPL-08', 'deskripsi' => 'Lulusan mampu berfungsi secara efektif sebagai individu maupun sebagai anggota atau pemimpin dalam tim yang beragam, inklusif, dan multidisiplin, baik secara langsung maupun jarak jauh.', 'created_at' => '2026-05-09 20:29:03', 'updated_at' => '2026-05-09 20:29:03'],
            ['id' => 10, 'kode' => 'CPL-09', 'deskripsi' => 'Lulusan mampu menyampaikan gagasan dan informasi keteknikan secara efektif dan inklusif kepada kalangan profesional maupun masyarakat umum.', 'created_at' => '2026-05-09 20:29:12', 'updated_at' => '2026-05-09 20:29:12'],
            ['id' => 11, 'kode' => 'CPL-10', 'deskripsi' => 'Lulusan mampu menerapkan prinsip-prinsip manajemen rekayasa dan keuangan dalam pengelolaan proyek rekayasa perangkat lunak', 'created_at' => '2026-05-09 20:29:25', 'updated_at' => '2026-05-09 20:29:25'],
            ['id' => 12, 'kode' => 'CPL-11', 'deskripsi' => 'Lulusan memiliki kemampuan intelektual untuk berpikir secara mandiri dan kritis sebagai pembelajar sepanjang hayat, memiliki kemauan belajar dan motivasi diri untuk mengetahui dan menguasai hal-hal baru melalui pendidikan lanjut formal, pendidikan nonformal, maupun aktivitas pengembangan diri lainnya dengan keterampilan sosial dan kepemimpinan yang baik, dan menunjukkan rasa tanggung jawab.', 'created_at' => '2026-05-09 20:29:37', 'updated_at' => '2026-05-09 20:29:37']
        ]);

        // Seed IEAs
        DB::table('ieas')->insert([
            ['id' => 1, 'kode' => 'IEA_A', 'deskripsi' => 'Engineering Knowledge : Kemampuan menerapkan pengetahuan matematika, ilmu alam, komputasi, dasar-dasar rekayasa, dan suatu spesialisasi keteknikan pada prosedur, proses, sistem, atau metodologi keteknikan terapan tertentu. (Engineering Knowledge)', 'created_at' => '2026-05-09 20:34:12', 'updated_at' => '2026-05-09 20:34:12'],
            ['id' => 2, 'kode' => 'IEA_B', 'deskripsi' => 'Problem Analysis :	Kemampuan mengidentifikasi, merumuskan, meneliti literatur dan menganalisis masalah teknik yang terdefinisi secara luas guna mencapai kesimpulan yang dibuktikan, dengan menggunakan alat bantu analisis yang sesuai dengan disiplin atau bidang spesialisasi. (Problem Analysis)', 'created_at' => '2026-05-09 20:34:23', 'updated_at' => '2026-05-09 20:34:23'],
            ['id' => 3, 'kode' => 'IEA_C', 'deskripsi' => 'Design/Development of Solutions :	Kemampuan merancang solusi untuk masalah teknologi rekayasa yang didefinisikan secara luas dan berkontribusi pada desain sistem, komponen atau proses untuk memenuhi kebutuhan yang teridentifikasi dengan pertimbangan yang tepat untuk kesehatan dan keselamatan masyarakat, biaya seumur hidup, nol karbon, serta sumber daya, pertimbangan budaya, sosial, dan lingkungan sesuai kebutuhan. (Design/development of solution)', 'created_at' => '2026-05-09 20:35:19', 'updated_at' => '2026-05-09 20:35:19'],
            ['id' => 4, 'kode' => 'IEA_D', 'deskripsi' => 'Investigation :	Kemampuan melakukan investigasi terhadap masalah teknik yang terdefinisi secara luas; menemukan, mencari dan memilih data yang relevan dari standar, basis data maupun literatur, merancang dan melakukan eksperimen untuk memberikan kesimpulan yang absah. (Investigation)', 'created_at' => '2026-05-09 20:35:33', 'updated_at' => '2026-05-09 20:35:33'],
            ['id' => 5, 'kode' => 'IEA_E', 'deskripsi' => 'Modern Tool Usage :	Kemampuan memilih, menerapkan, dan mengenali keterbatasan penerapan suatu metoda, sumber daya, maupun alat bantu rekayasa dan teknologi informasi, termasuk prediksi dan pemodelan, bagi permasalahan teknik yang terdefinisi secara luas. (Tool Usage)', 'created_at' => '2026-05-09 20:35:41', 'updated_at' => '2026-05-09 20:35:41'],
            ['id' => 6, 'kode' => 'IEA_F', 'deskripsi' => 'The Engineer and Society :	Kemampuan menganalisis dan mengevaluasi dampak terhadap masyarakat, ekonomi, keberlanjutan, kesehatan dan keselamatan, hukum dan peraturan, serta lingkungan dari upaya pemecahan permasalahan teknik yang terdefinisi secara luas. (The engineer and The world)', 'created_at' => '2026-05-09 20:35:49', 'updated_at' => '2026-05-09 20:35:49'],
            ['id' => 7, 'kode' => 'IEA_G', 'deskripsi' => 'Ethics :	Kemampuan untuk memahami dan berkomitmen pada etika profesi dan norma praktik teknologi rekayasa termasuk kepatuhan terhadap hukum nasional dan internasional. (Ethics)', 'created_at' => '2026-05-09 20:35:56', 'updated_at' => '2026-05-09 20:35:56'],
            ['id' => 8, 'kode' => 'IEA_H', 'deskripsi' => 'Individual and Teamwork :	Kemampuan untuk berfungsi secara efektif sebagai individu, dan sebagai anggota atau pemimpin dalam tim yang beragam dan inklusif dan dalam pengaturan multi-disiplin, tatap muka, jarak jauh dan terdistribusi. (Individual and Team Work)', 'created_at' => '2026-05-09 20:36:02', 'updated_at' => '2026-05-09 20:36:02'],
            ['id' => 9, 'kode' => 'IEA_I', 'deskripsi' => 'Communication :	Kemampuan berkomunikasi secara efektif dan inklusif pada aktivitas keinsinyuran dengan komunitas teknik dan dengan masyarakat luas. (Communication)', 'created_at' => '2026-05-09 20:36:09', 'updated_at' => '2026-05-09 20:36:09'],
            ['id' => 10, 'kode' => 'IEA_J', 'deskripsi' => 'Project Management and Finance :	Kemampuan menerapkan pengetahuan dan pemahaman prinsip-prinsip manajemen rekayasa. (Project Manajement and Finance)', 'created_at' => '2026-05-09 20:36:15', 'updated_at' => '2026-05-09 20:36:15'],
            ['id' => 11, 'kode' => 'IEA_K', 'deskripsi' => 'Life-long Learning :	Kemampuan untuk mengenali kebutuhan, dan memiliki kemampuan untuk belajar mandiri dan seumur hidup serta berpikir kritis dalam menghadapi spesialisasi teknologi baru. (Lifelong Learning)', 'created_at' => '2026-05-09 20:36:25', 'updated_at' => '2026-05-09 20:36:25']
        ]);
        // Seed PPMs
        DB::table('ppms')->insert([
            ['id' => 10, 'kode' => 'PPM-01', 'deskripsi' => 'Lulusan dapat menggunakan pengalaman akademis dari perkuliahan, demonstrasi, eksperimen, proyek dan laboratorium, dan akan menerapkan pengetahuan teknis mendalam yang diperoleh di bidang informatika sebagai ahli perekayasa perangkat cerdas dan sistem tertanam berbasis otomasi manufaktur pada Manufacturing Execution System dan Enterprise Resource Planning dan akan berhasil menerapkan teknik analisis dan keterampilan pemecahan masalah yang diperlukan untuk beradaptasi dengan perubahan teknologi dan untuk berkarir di industri manufaktur.', 'created_at' => '2026-05-09 20:32:31', 'updated_at' => '2026-05-09 20:32:31'],
            ['id' => 11, 'kode' => 'PPM-02', 'deskripsi' => 'Lulusan dapat mengembangkan kemampuan diri untuk mengembangkan aplikasi perangkat lunak, konsultansi   perangkat   lunak,   membuat perangkat   lunak,   dan   melakukan   pengujian untuk memverifikasi fungsionalitas perangkat lunak. Mampu mengembangkan (Programmer), menguji dan memvalidasi (Quality Assurance) perangkat lunak pada Manufacturing Execution System dan Enterprise Resource Planning.', 'created_at' => '2026-05-09 20:32:42', 'updated_at' => '2026-05-09 20:32:42'],
            ['id' => 12, 'kode' => 'PPM-03', 'deskripsi' => 'Lulusan dapat mengembangkan diri melalui studi lanjut atau berwirausaha pada bidang Informatika, Sistem Siber-Fisik dan Otomasi Manufaktur.', 'created_at' => '2026-05-09 20:32:52', 'updated_at' => '2026-05-09 20:32:52'],
            ['id' => 13, 'kode' => 'PPM-04', 'deskripsi' => 'Lulusan akan menunjukkan profesionalisme dan etika, termasuk komitmen terhadap kualitas kinerja dan ketepatan waktu, menghormati keragaman, dan kesadaran akan isu-isu internasional; dan akan memulai pengembangan profesional berkelanjutan yang menunjukkan komitmen mereka terhadap tanggung jawab sebagai ahli teknologi teknik kontemporer sepanjang karir mereka.', 'created_at' => '2026-05-09 20:33:02', 'updated_at' => '2026-05-09 20:33:02'],
            ['id' => 14, 'kode' => 'PPM-05', 'deskripsi' => 'Lulusan memiliki kemampuan untuk berperan aktif dalam hal yang terkait sikap seorang intelektual seperti kritis, analitis, dan mampu menghasilkan karya ilmiah yang dapat berkontribusi terhadap perkembangan ilmu pengetahuan', 'created_at' => '2026-05-09 20:33:14', 'updated_at' => '2026-05-09 20:33:14']
        ]);

        // Seed Indikator Kinerjas
        DB::table('indikator_kinerjas')->insert([
            ['id' => 1, 'cpl_id' => 1, 'kode' => 'A-1', 'deskripsi' => 'Menerapkan metode data science dan algoritma komputasi untuk memproses dan menganalisis set data kompleks pada sistem industri.', 'created_at' => '2026-05-09 20:37:06', 'updated_at' => '2026-05-09 20:37:06'],
            ['id' => 2, 'cpl_id' => 1, 'kode' => 'A-2', 'deskripsi' => 'Menggunakan prinsip dasar rekayasa informatika dalam merancang prosedur, pemodelan matematis, dan logika sistem komputasi terapan.', 'created_at' => '2026-05-09 20:37:21', 'updated_at' => '2026-05-09 20:37:21'],
            ['id' => 3, 'cpl_id' => 2, 'kode' => 'B-1', 'deskripsi' => 'Merancang arsitektur perangkat lunak yang memiliki performa tinggi (high performance), stabil, dan minim bug saat menangani beban kerja besar.', 'created_at' => '2026-05-09 20:37:41', 'updated_at' => '2026-05-09 20:37:41'],
            ['id' => 4, 'cpl_id' => 2, 'kode' => 'B-2', 'deskripsi' => 'Mengembangkan dan mengimplementasikan algoritma cerdas (seperti Machine Learning atau otomasi cerdas) untuk meningkatkan kemampuan pengambilan keputusan dalam sistem manufaktur.', 'created_at' => '2026-05-09 20:38:03', 'updated_at' => '2026-05-09 20:38:03'],
            ['id' => 5, 'cpl_id' => 4, 'kode' => 'C-1', 'deskripsi' => 'Merancang solusi teknologi informasi yang efisien dalam penggunaan sumber daya (resource-efficient), seperti optimasi penggunaan memori, storage, atau kapasitas server.', 'created_at' => '2026-05-09 20:38:20', 'updated_at' => '2026-05-09 20:38:20'],
            ['id' => 6, 'cpl_id' => 4, 'kode' => 'C-2', 'deskripsi' => 'Mengintegrasikan protokol keamanan (cybersecurity) dan standar keselamatan sistem, serta menerapkan prinsip green computing untuk meminimalisasi jejak karbon dari infrastruktur IT.', 'created_at' => '2026-05-09 20:38:38', 'updated_at' => '2026-05-09 20:38:38'],
            ['id' => 7, 'cpl_id' => 5, 'kode' => 'D-1', 'deskripsi' => 'Mengelola basis data terpusat berskala enterprise (seperti pada sistem MES atau ERP) untuk menjamin integritas, ketersediaan, dan keamanan informasi.', 'created_at' => '2026-05-09 20:38:57', 'updated_at' => '2026-05-09 20:38:57'],
            ['id' => 8, 'cpl_id' => 5, 'kode' => 'D-2', 'deskripsi' => 'Membangun antarmuka (dashboard analitik) untuk melakukan pemantauan (monitoring) aliran data operasional industri secara real-time.', 'created_at' => '2026-05-09 20:39:10', 'updated_at' => '2026-05-09 20:39:10'],
            ['id' => 9, 'cpl_id' => 5, 'kode' => 'D-3', 'deskripsi' => 'Melakukan prosedur system maintenance, pembaruan versi, dan troubleshooting agar sistem enterprise tetap beroperasi dengan downtime seminimal mungkin.', 'created_at' => '2026-05-09 20:39:32', 'updated_at' => '2026-05-09 20:39:32'],
            ['id' => 10, 'cpl_id' => 6, 'kode' => 'E-1', 'deskripsi' => 'Membangun Application Programming Interface (API) atau middleware untuk mengintegrasikan berbagai perangkat lunak dan mesin (IoT) guna mendukung otomasi industri.', 'created_at' => '2026-05-09 20:39:46', 'updated_at' => '2026-05-09 20:39:46'],
            ['id' => 11, 'cpl_id' => 6, 'kode' => 'E-2', 'deskripsi' => 'Menerapkan pemikiran kritis dalam melakukan debugging, refactoring kode, dan memecahkan masalah logika yang rumit selama siklus pengembangan perangkat lunak (SDLC).', 'created_at' => '2026-05-09 20:40:00', 'updated_at' => '2026-05-09 20:40:00'],
            ['id' => 12, 'cpl_id' => 6, 'kode' => 'E-3', 'deskripsi' => 'Mendemonstrasikan ide rancangan sistem melalui wireframe, purwarupa (prototype), atau diagram UML (Use Case, Activity Diagram) secara jelas dan terstruktur.', 'created_at' => '2026-05-09 20:40:17', 'updated_at' => '2026-05-09 20:40:17'],
            ['id' => 13, 'cpl_id' => 7, 'kode' => 'F-1', 'deskripsi' => 'Mengevaluasi dampak digitalisasi atau penerapan otomatisasi perangkat lunak terhadap kondisi sosial pekerja dan efisiensi ekonomi perusahaan.', 'created_at' => '2026-05-09 20:40:30', 'updated_at' => '2026-05-09 20:40:30'],
            ['id' => 14, 'cpl_id' => 7, 'kode' => 'F-2', 'deskripsi' => 'Menganalisis kepatuhan sistem yang dirancang terhadap regulasi hukum yang berlaku (seperti Undang-Undang ITE dan standar perlindungan privasi data pengguna/UU PDP).', 'created_at' => '2026-05-09 20:40:45', 'updated_at' => '2026-05-09 20:40:45'],
            ['id' => 15, 'cpl_id' => 8, 'kode' => 'G-1', 'deskripsi' => 'Menjunjung tinggi kode etik profesional TI dengan tidak menyalahgunakan akses data (data breach) dan menjaga kerahasiaan informasi perusahaan.', 'created_at' => '2026-05-09 20:41:04', 'updated_at' => '2026-05-09 20:41:04'],
            ['id' => 16, 'cpl_id' => 8, 'kode' => 'G-2', 'deskripsi' => 'Mematuhi lisensi perangkat lunak (software licensing), menghindari plagiarisme source code, dan menghargai Hak Kekayaan Intelektual (HKI) pencipta lain.', 'created_at' => '2026-05-09 20:41:23', 'updated_at' => '2026-05-09 20:41:23'],
            ['id' => 17, 'cpl_id' => 9, 'kode' => 'H-1', 'deskripsi' => 'Berkolaborasi secara produktif dalam tim pengembangan (sebagai Developer, UI/UX Designer, atau System Analyst), menghargai keragaman, dan menciptakan lingkungan kerja yang inklusif.', 'created_at' => '2026-05-09 20:41:44', 'updated_at' => '2026-05-09 20:41:44'],
            ['id' => 18, 'cpl_id' => 9, 'kode' => 'H-2', 'deskripsi' => 'Menggunakan perangkat kolaborasi jarak jauh (seperti Git, GitHub/GitLab, Jira, Trello) untuk berkoordinasi secara efektif dalam lingkungan kerja hibrida atau multinasional.', 'created_at' => '2026-05-09 20:42:02', 'updated_at' => '2026-05-09 20:42:02'],
            ['id' => 19, 'cpl_id' => 10, 'kode' => 'I-1', 'deskripsi' => 'Menyusun dokumentasi teknis, API documentation, dan manual pengguna (user manual) dengan bahasa yang mudah dipahami oleh rekan pengembang maupun pengguna akhir (end-user).', 'created_at' => '2026-05-09 20:42:21', 'updated_at' => '2026-05-09 20:42:21'],
            ['id' => 20, 'cpl_id' => 10, 'kode' => 'I-2', 'deskripsi' => 'Mempresentasikan kemajuan proyek (Sprint Review) atau peluncuran produk secara meyakinkan kepada klien, manajemen, atau masyarakat umum tanpa menggunakan jargon teknis yang membingungkan.', 'created_at' => '2026-05-09 20:42:38', 'updated_at' => '2026-05-09 20:42:38'],
            ['id' => 21, 'cpl_id' => 11, 'kode' => 'J-1', 'deskripsi' => 'Menyusun perencanaan proyek perangkat lunak (Agile/Scrum) yang mencakup penjadwalan iterasi (sprint), pembagian tugas, dan pengelolaan risiko proyek.', 'created_at' => '2026-05-09 20:42:54', 'updated_at' => '2026-05-09 20:42:54'],
            ['id' => 22, 'cpl_id' => 11, 'kode' => 'J-2', 'deskripsi' => 'Menyusun Rencana Anggaran Biaya (RAB) secara efisien untuk kebutuhan proyek IT, termasuk perhitungan biaya hosting, layanan cloud (AWS/Google Cloud), dan lisensi aplikasi pihak ketiga.', 'created_at' => '2026-05-09 20:43:09', 'updated_at' => '2026-05-09 20:43:09'],
            ['id' => 23, 'cpl_id' => 12, 'kode' => 'K-1', 'deskripsi' => 'Menunjukkan inisiatif mandiri untuk mengikuti perkembangan teknologi terbaru (seperti mempelajari framework modern, bahasa pemrograman baru, atau mengambil sertifikasi profesional).', 'created_at' => '2026-05-09 20:43:27', 'updated_at' => '2026-05-09 20:43:27'],
            ['id' => 24, 'cpl_id' => 12, 'kode' => 'K-2', 'deskripsi' => 'Mengembangkan kemampuan kepemimpinan dan jejaring sosial (networking) untuk berkontribusi secara berkelanjutan dalam komunitas teknologi atau industri.', 'created_at' => '2026-05-09 20:43:41', 'updated_at' => '2026-05-09 20:43:41']
        ]);


    }
}